const express = require("express");
const path = require("path");
const fs = require("fs");
const { ATTACHMENTS_DIR } = require("../storage");

const router = express.Router();

// Filenames are only ever generated by storage.js (timestamp + nanoid),
// never taken from user input elsewhere -- this pattern check is just a
// second guard against path traversal on top of that.
const SAFE_FILENAME = /^[A-Za-z0-9_-]+\.[A-Za-z0-9]+$/;

router.get("/:filename", (req, res) => {
  const { filename } = req.params;
  if (!SAFE_FILENAME.test(filename)) return res.status(400).json({ error: "invalid filename" });

  const filePath = path.join(ATTACHMENTS_DIR, filename);
  if (!fs.existsSync(filePath)) return res.status(404).json({ error: "not found" });

  res.sendFile(filePath);
});

module.exports = router;
